
/*******************************************************************************
 * generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
 * image
 * filename: unsaved
 * name: bt_icon
 *
 * preset name: Monochrome
 * data block size: 8 bit(s), uint8_t
 * RLE compression enabled: no
 * conversion type: Monochrome, Edge 0
 * split to rows: yes
 * bits per pixel: 1
 *
 * preprocess:
 *  main scan direction: top_to_bottom
 *  line scan direction: forward
 *  inverse: no
 *******************************************************************************/

#include <stdint.h>

#include "icon_data.h"

static const uint8_t image_data_bt_icon[90] PROGMEM = {
    // ∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙████∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙█████∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙██████∙∙∙∙
    // ∙∙∙∙∙∙∙∙███████∙∙∙
    // ∙██∙∙∙∙∙███∙████∙∙
    // ████∙∙∙∙███∙∙████∙
    // █████∙∙∙███∙∙∙████
    // ∙█████∙∙███∙∙∙∙███
    // ∙∙█████∙███∙∙∙████
    // ∙∙∙████████∙∙████∙
    // ∙∙∙∙███████∙████∙∙
    // ∙∙∙∙∙██████████∙∙∙
    // ∙∙∙∙∙∙████████∙∙∙∙
    // ∙∙∙∙∙∙∙██████∙∙∙∙∙
    // ∙∙∙∙∙∙∙██████∙∙∙∙∙
    // ∙∙∙∙∙∙████████∙∙∙∙
    // ∙∙∙∙∙██████████∙∙∙
    // ∙∙∙∙███████∙████∙∙
    // ∙∙∙████████∙∙████∙
    // ∙∙█████∙███∙∙∙████
    // ∙█████∙∙███∙∙∙∙███
    // █████∙∙∙███∙∙∙████
    // ████∙∙∙∙███∙∙████∙
    // ∙██∙∙∙∙∙███∙████∙∙
    // ∙∙∙∙∙∙∙∙███████∙∙∙
    // ∙∙∙∙∙∙∙∙██████∙∙∙∙
    // ∙∙∙∙∙∙∙∙█████∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙████∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙
    0x00, 0xe0, 0x00,
    0x00, 0xf0, 0x00,
    0x00, 0xf8, 0x00,
    0x00, 0xfc, 0x00,
    0x00, 0xfe, 0x00,
    0x60, 0xef, 0x00,
    0xf0, 0xe7, 0x80,
    0xf8, 0xe3, 0xc0,
    0x7c, 0xe1, 0xc0,
    0x3e, 0xe3, 0xc0,
    0x1f, 0xe7, 0x80,
    0x0f, 0xef, 0x00,
    0x07, 0xfe, 0x00,
    0x03, 0xfc, 0x00,
    0x01, 0xf8, 0x00,
    0x01, 0xf8, 0x00,
    0x03, 0xfc, 0x00,
    0x07, 0xfe, 0x00,
    0x0f, 0xef, 0x00,
    0x1f, 0xe7, 0x80,
    0x3e, 0xe3, 0xc0,
    0x7c, 0xe1, 0xc0,
    0xf8, 0xe3, 0xc0,
    0xf0, 0xe7, 0x80,
    0x60, 0xef, 0x00,
    0x00, 0xfe, 0x00,
    0x00, 0xfc, 0x00,
    0x00, 0xf8, 0x00,
    0x00, 0xf0, 0x00,
    0x00, 0xe0, 0x00};
const tImage bt_icon = {image_data_bt_icon, 18, 30, 8};
